---
- name: EC2 - Public | Create bastion host
  local_action:
    module: ec2
    group: "{{}}"
    key_name: "{{ key_name }}"
    instance_type: t2.micro
    image: ami-b63769a1 
    vpc_subnet_id: public_subnet_id
    assign_public_ip: True
    wait: True
    instance_tags:
      Name: "{{ vpc_name }}_bastion"
      Role: "bastion"
  register: bastion

- name: EC2 - Public | Create web host
  local_action:
    module: ec2
    group: "{{ }}"
    key_name: "{{ key_name }}"
    instance_type: t2.micro
    image: ami-b63769a1
    vpc_subnet_id: public_subnet_id
    assign_public_ip: True
    wait: True
    instance_tags:
      Name: "{{ vpc_name }}_web"
      Role: "webhost"
  register: web

- name: EC2 - Public | Wait for Bastion's SSH to come up
  local_action:
    module: wait_for
    host: "{{ bastion.instances[0].public_ip }}"
    port: 22
    state: started
