---
- name: Create a AWS VPC inside mentioned region
  ec2_vpc_net:
    name: "{{ vpc_name }}-vpc"
    region: "{{ vpc_region }}"
    state: present
    cidr_block: "{{ vpc_cidr_block }}"
    tenancy: default
  register: vpc

- name: Set up subnets
  ec2_vpc_subnet:
    state: present
    region: "{{ vpc_region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ item.cidr }}"
    tags:
      Name: "{{ vpc_name }}-{{ item.name }}"
  with_items: "{{ vpc_subnets }}"
  register: subnets

- name: Add internet gateway
  ec2_vpc_igw:
    region: "{{ vpc_region }}"
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
  register: igw

- name: Add Public subnet(s) route 
  ec2_vpc_route_table:
    region: "{{ vpc_region }}"
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    tags:
      Name: "{{ vpc_name }}-public"
    subnets: "{{ item.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  with_items: "{{ subnets.results }}"
  when: '"public" in item.subnet.tags.Name'
  register: publicroutetable

- name: Tag the internet gateway
  ec2_tag:
    region: "{{ vpc_region }}"
    resource: "{{ igw.gateway_id }}"
    state: present
    tags:
      Name: "{{ vpc_name }}-igw"

- name: Create NAT gateway
  ec2_vpc_nat_gateway:
    region: "{{ vpc_region }}"
    state: present
    subnet_id: "{{ item.subnet.id }}"
    wait: yes
    if_exist_do_not_create: True
  with_items: "{{ subnets.results }}"
  when: '"private" in item.subnet.tags.Name'
  register: natgateway 

- name: Create .yml file inside the secret_vars directory
  lineinfile:
    dest: "secret_vars/{{ vpc_name }}.yml"
    line: "---"
    create: yes

- name: "Write vpc info to {{ vpc_name }}.yml file inside the secret_vars directory"
  lineinfile:
    dest: "secret_vars/{{ vpc_name }}.yml"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }}: {{ '\"' + item.line + '\"' }}"
  with_items:
    - { regexp: 'vpc_id', line: '{{ vpc.vpc.id }}' }
    - { regexp: 'igw', line: '{{ igw.gateway_id }}' }
    - { regexp: 'vpc_region', line: '{{ vpc_region }}' }

- include_vars: "secret_vars/{{ vpc_name }}.yml"
