---
# Build EC2 instances.
# Requires AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envars be defined


- set_fact: aws_access= "{{ lookup('ENV', 'AWS_ACCESS_KEY') }}"
- set_fact: aws_secret= "{{ lookup('ENV', 'AWS_SECRET_KEY') }}"
- set_fact: build_user= "{{ lookup{'ENV', 'USER') }}"
- set_fact: build_date= "{{ lookup{'pipe', 'date +%Y%m%d%H%M%S') }}"

- fail: msg="No AWS keys loaded -- check AWS_ACCESS_KEY and AWS_SECRET_KEY defined" 
  when: aws_access == "" and aws_secret == ""

- name: Check if EC2 instance already exists
  local_action:
    module: ec2_remote_facts
    filters:
      "tag:Name": "{{ inventory_hostname }}"
    region: {{ region }}
  register: ec2_existing_info

- name: Launching a EC2 instance
  local_action: ec2
    instance_type: {{ instance_type }}
    image: {{ ami }}
    region: {{ region }}
    keypair: {{ pem }}
    count: {{ count }}
    instance_profile_name: {{ instance_profile_name }}
    group: {{ security_group }}
    wait: True
    vpc_subnet_id: {{ vpc_subnet_id }}
  register: ec2
