---
- name: EC2 SG | Create an EC2 security group inside the mentioned VPC
  ec2_group:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    region: "{{ vpc_region }}"
    vpc_id: "{{ 
